server:
  port: 8888

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=ms-trx-hist-svc}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate.ddl-auto: none
    show-sql: ${DB_SHOW_SQL:true}

  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

  security:
    user:
      name: ${BASIC_AUTH_USERNAME:hendraptr}
      password: ${BASIC_AUTH_PASSWORD:hendraptr123}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

logging:
  level:
    com.assessment.mstrxhistsvc: ${LOG_LEVEL:INFO}