CREATE TABLE t_trx_history (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ACCOUNT_NUMBER VARCHAR(20),
    TRX_AMOUNT DECIMAL(12, 2),
    DESCRIPTION TEXT,
    TRX_DATE DATE,
    TRX_TIME TIME,
    CUSTOMER_ID VARCHAR(10),
    VERSION INT
);